name: Add Project
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
      url:
        description: 'Repo URL'
        required: true
concurrency:
    group: add-project
    cancel-in-progress: false
jobs:
  version-bump:
    name: Add Project
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Source
         uses: actions/checkout@v2
       - name: Add project as submodule
         run: |
            git config pull.rebase true || true
            git pull || true
            git submodule add ${{ github.event.inputs.url }} "${{ github.event.inputs.name }}"
       - name: Commit changes
         run: |
            git config user.name bot
            git config user.email bot@nikjos.in
            git add --all || true
            git commit -m "Added New Submodule" || true
            git push --quiet
