name: Add Project
on:
  workflow_dispatch:
    inputs:
      index:
        description: 'Index Number'
        required: true
      repo_name:
        description: 'Repository Name (user/repo)'
        required: true
      api_name:
        description: 'API Name'
        required: true
      live_url:
        description: 'Hosted URL of the project'        
concurrency:
    group: add-project
    cancel-in-progress: false
jobs:
  version-bump:
    name: Add Project
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Source
         uses: actions/checkout@v2
       - name: Add project as submodule
         run: |
            git config pull.rebase true || true
            git pull || true
            git submodule add https://github.com/${{ github.event.inputs.repo_name }} "${{ github.event.inputs.index }}-${{ github.event.inputs.api_name }}-API"
       - name: Commit changes
         run: |
            git config user.name nikiljos-bot
            git config user.email bot@nikjos.in
            git add --all || true
            git commit -m "Added ${{ github.event.inputs.api_name }}" || true
            git push --quiet
